version: "3.8"
services:
  dev:
    image: node:current-alpine
    working_dir: /engine
    expose:
      - 28080
    ports:
      - "28080:28080"
    volumes:
      - ./engine:/engine
    command: "yarn serve"
  app:
    image: nginx:alpine
    expose:
      - 80
    ports:
      - "18080:80"
    volumes:
      - ./engine/dist:/usr/share/nginx/html:ro
